# Generated by Django 5.1.5 on 2025-04-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_create_comment', 'Can create comment'), ('can_delete_comment', 'Can delete comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_create_post', 'Can create post'), ('can_edit_post', 'Can edit post'), ('can_delete_post', 'Can delete post')]},
        ),
    ]
